server:
  port: 9141
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dormitory_manager?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  devtools:
    restart:
      enabled: true
  jackson:
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rabbiter.dm.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  reasonable: true
constant:
  upload-path: D:/upload/
logging:
  level:
    com.rabbiter.dm.aop: info